from .client import RouterAI
from .errors import (
    APIConnectionError,
    APIStatusError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    ConfigurationError,
    ConflictError,
    DeadlineExceededError,
    ErrorInfo,
    InsufficientFundsError,
    ModelNotFoundError,
    NoProviderError,
    NotFoundError,
    PermissionDeniedError,
    RateLimitError,
    RequestError,
    ResponseParsingError,
    RouterAIError,
    ServerError,
    StreamInterruptedError,
    UnprocessableEntityError,
    VideoGenerationError,
    WebhookVerificationError,
)
from .registry import Registry
from .resources.audio import SpeechResult, TranscriptionResult
from .resources.chat import AudioDelta, StreamAccumulator, StreamChunk
from .resources.completions import CompletionChoice, CompletionsResult
from .resources.embeddings import EmbeddingsResult, RerankResult
from .resources.images import GeneratedImage, ImageResult, ImageStreamChunk
from .resources.videos import FrameImage, ImageReference, VideoTask
from .schemas import (
    Architecture,
    Capability,
    ChatResult,
    Endpoint,
    GenerationInfo,
    KeyInfo,
    MemberCreation,
    MessagesResult,
    Model,
    ModelDetail,
    ModelPricing,
    ProviderSelection,
    ResponsesResult,
    ServiceTier,
    TeamInvitation,
    TeamMember,
    ToolCall,
    Usage,
)
from .webhooks import signing_secret, verify_video

__version__: str
try:
    from importlib.metadata import version

    __version__ = version("routerai")
except Exception:  # pragma: no cover - source checkout without installed metadata
    __version__ = "0.1.1"

__all__ = [
    "APIConnectionError",
    "APIStatusError",
    "APITimeoutError",
    "Architecture",
    "AudioDelta",
    "AuthenticationError",
    "BadRequestError",
    "Capability",
    "ChatResult",
    "CompletionChoice",
    "CompletionsResult",
    "ConfigurationError",
    "ConflictError",
    "DeadlineExceededError",
    "EmbeddingsResult",
    "Endpoint",
    "ErrorInfo",
    "FrameImage",
    "GeneratedImage",
    "GenerationInfo",
    "ImageReference",
    "ImageResult",
    "ImageStreamChunk",
    "InsufficientFundsError",
    "KeyInfo",
    "MemberCreation",
    "MessagesResult",
    "Model",
    "ModelDetail",
    "ModelNotFoundError",
    "ModelPricing",
    "NoProviderError",
    "NotFoundError",
    "PermissionDeniedError",
    "ProviderSelection",
    "RateLimitError",
    "Registry",
    "RequestError",
    "RerankResult",
    "ResponseParsingError",
    "ResponsesResult",
    "RouterAI",
    "RouterAIError",
    "ServerError",
    "ServiceTier",
    "SpeechResult",
    "StreamAccumulator",
    "StreamChunk",
    "StreamInterruptedError",
    "TeamInvitation",
    "TeamMember",
    "ToolCall",
    "TranscriptionResult",
    "UnprocessableEntityError",
    "Usage",
    "VideoGenerationError",
    "VideoTask",
    "WebhookVerificationError",
    "__version__",
    "signing_secret",
    "verify_video",
]
