from .client import RouterAI
from .errors import (
    APIStatusError,
    AuthenticationError,
    ConfigurationError,
    InsufficientFundsError,
    ModelNotFoundError,
    NoProviderError,
    NotFoundError,
    PermissionDeniedError,
    RateLimitError,
    RequestError,
    RouterAIError,
    StreamInterruptedError,
    VideoGenerationError,
)
from .registry import Registry
from .resources.videos import FrameImage, ImageReference
from .schemas import (
    Architecture,
    Capability,
    ChatResult,
    Endpoint,
    KeyInfo,
    MemberCreation,
    MessagesResult,
    Model,
    ModelDetail,
    ModelPricing,
    ProviderSelection,
    ResponsesResult,
    ServiceTier,
    TeamInvitation,
    TeamMember,
    ToolCall,
    Usage,
)

__version__ = "0.1.0"

__all__ = [
    "APIStatusError",
    "Architecture",
    "AuthenticationError",
    "Capability",
    "ChatResult",
    "ConfigurationError",
    "Endpoint",
    "FrameImage",
    "ImageReference",
    "InsufficientFundsError",
    "KeyInfo",
    "MemberCreation",
    "MessagesResult",
    "Model",
    "ModelDetail",
    "ModelNotFoundError",
    "ModelPricing",
    "NoProviderError",
    "NotFoundError",
    "PermissionDeniedError",
    "ProviderSelection",
    "RateLimitError",
    "Registry",
    "RequestError",
    "ResponsesResult",
    "RouterAI",
    "RouterAIError",
    "ServiceTier",
    "StreamInterruptedError",
    "TeamInvitation",
    "TeamMember",
    "ToolCall",
    "Usage",
    "VideoGenerationError",
    "__version__",
]
